version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
      - 8443:443
    links:
      - db
    volumes:
      - /var/www/html/sysPass/app/config
      - /var/www/html/sysPass/app/backup
  db:
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=syspass
    ports:
      - 13306:33076
    volumes:
      - /var/lib/mysql
